trigger:
  - main  # Adjust to your branch

pool:
  vmImage: 'ubuntu-latest'  # Runs on an Ubuntu agent

variables:
  - template: /variables/variables.yaml  
  - group: "ACA_Variables"

steps:
  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: $(AzureSubscription)  # Ensure this is correctly defined
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Successfully authenticated to Azure."

  - task: AzureCLI@2
    displayName: 'Docker Login to Azure Container Registry'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Logging into Azure Container Registry..."
        az acr login --name "$(ACR_NAME)"

  - task: AzureCLI@2
    displayName: 'Pull, Tag, and Push Falcon Sensor'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Fetching latest Falcon container sensor..."
        LATESTSENSOR=$(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh | bash -s -t falcon-container | tail -1)
        echo "Tagging and pushing sensor image..."
        docker tag "$LATESTSENSOR" "$(MY_REPO):latest"
        docker push "$(MY_REPO):latest"

  - task: AzureCLI@2
    displayName: 'Extract Falconutil'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Extracting falconutil..."
        CONTAINER_ID=$(docker create "$(MY_REPO):latest")
        docker cp "$CONTAINER_ID:/usr/bin/falconutil" /tmp
        docker rm -v "$CONTAINER_ID"

  - task: AzureCLI@2
    displayName: 'Patch Vulnerable Image'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Patching vulnerable application image..."
        /tmp/falconutil patch-image aci \
          --source-image-uri "$(SOURCE_IMAGE)" \
          --target-image-uri "$(TARGET_IMAGE)" \
          --falcon-image-uri "$(MY_REPO):latest" \
          --cid "$(FALCON_CID)" \
          --container "$(CONTAINER_NAME)" \
          --container-group "$(CONTAINER_GROUP_NAME)" \
          --resource-group "$(RESOURCE_GROUP)" \
          --subscription "$(SUBSCRIPTION_ID)"

  - task: AzureCLI@2
    displayName: 'Push Patched Image'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Pushing patched image..."
        docker push "$(TARGET_IMAGE)"

  - task: AzureCLI@2
    displayName: 'Deploy to Azure Container Apps'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Deploying patched container to Azure Container Apps..."
        az containerapp update \
          --name "$(CONTAINER_APP_NAME)" \
          --resource-group "$(RESOURCE_GROUP)" \
          --image "$(TARGET_IMAGE)"
