trigger:
- main  # or whichever branch you want to trigger the pipeline on

variables:
- template: variables/variables.yaml
- group: "ACA_VARIABLES"
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(MY_REPO)'
    command: 'login'
    DockerRegistryEndpoint: 'AzureContainerRegistry' # Replace with your registry service connection name

- script: |
    echo $(FALCON_CLIENT_ID) > falcon_client_id.txt
    echo $(FALCON_CLIENT_SECRET) > falcon_client_secret.txt
    echo $(FALCON_CID) > falcon_cid.txt
    LATESTSENSOR=$(bash <(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh) -t falcon-container | tail -1) 
    echo $LATESTSENSOR
    docker tag $LATESTSENSOR $(MY_REPO):latest
    docker push $(MY_REPO):latest
  displayName: 'Download and Push Latest Falcon Sensor'

- script: |
    id=$(docker create $(MY_REPO):latest)
    docker cp $id:/usr/bin/falconutil /tmp
    docker rm -v $id
    /tmp/falconutil patch-image aci \
    --source-image-uri $(SOURCE_IMAGE) \
    --target-image-uri $(TARGET_IMAGE) \
    --falcon-image-uri $(MY_REPO):latest \
    --cid $(FALCON_CID) \
    --container $(CONTAINER_NAME) \
    --resource-group $(RESOURCE_GROUP) \
    --image-pull-policy Always \
    --container-group $(CONTAINER_GROUP) \
    --subscription $(SUBSCRIPTION_ID)
  displayName: 'Patch Image with Falcon Sensor'

