trigger:
- main  # or whichever branch you want to trigger the pipeline on

variables:
- template: variables/variables.yaml
- group: "ACA_VARIABLES"
  FALCON_CLIENT_ID: 'a908592983e34275ada9b8067c72c86f'
  FALCON_CLIENT_SECRET: 'T62WtLhKS1Oy5usY0EvAf8FoNGgp3B7Mcqe94jm'
  FALCON_CID: '5DDB0407BEF249C19C7A975F17979A1F-90'
  MY_REPO: 'teds2acr.azurecr.io/falcon-container'
  RESOURCE_GROUP: 'dvn-aks-virtual-node-test-rg'
  SUBSCRIPTION_ID: '62f48e64-fc12-4cac-a51c-02d5e413cdfe'
  CONTAINER_NAME: 'crwd_vulapp'
  CONTAINER_GROUP: 'virtual-node-aci-linux'
  SOURCE_IMAGE: 'quay.io/crowdstrike/vulnapp:latest'
  TARGET_IMAGE: 'teds2acr.azurecr.io/aci-vulapp:crwdv1'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(MY_REPO)'
    command: 'login'
    DockerRegistryEndpoint: 'AzureContainerRegistry' # Replace with your registry service connection name

- script: |
    echo $(FALCON_CLIENT_ID) > falcon_client_id.txt
    echo $(FALCON_CLIENT_SECRET) > falcon_client_secret.txt
    echo $(FALCON_CID) > falcon_cid.txt
    LATESTSENSOR=$(bash <(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh) -t falcon-container | tail -1) 
    echo $LATESTSENSOR
    docker tag $LATESTSENSOR $(MY_REPO):latest
    docker push $(MY_REPO):latest
  displayName: 'Download and Push Latest Falcon Sensor'

- script: |
    id=$(docker create $(MY_REPO):latest)
    docker cp $id:/usr/bin/falconutil /tmp
    docker rm -v $id
    /tmp/falconutil patch-image aci \
    --source-image-uri $(SOURCE_IMAGE) \
    --target-image-uri $(TARGET_IMAGE) \
    --falcon-image-uri $(MY_REPO):latest \
    --cid $(FALCON_CID) \
    --container $(CONTAINER_NAME) \
    --resource-group $(RESOURCE_GROUP) \
    --image-pull-policy Always \
    --container-group $(CONTAINER_GROUP) \
    --subscription $(SUBSCRIPTION_ID)
  displayName: 'Patch Image with Falcon Sensor'

